
import { format } from 'date-fns';
import { commonStyles } from './print/commonStyles';
import { dialogueStyles, generateDialogueHtml } from './print/dialogueTemplate';
import { monologueStyles, generateMonologueHtml } from './print/monologueTemplate';

interface PrintOptions {
    title: string;
    content: string;
    scriptType: 'MONOLOGUE' | 'DIALOGUE';
    ownerName?: string;
    formattedDuration: string;
}

/**
 * Professional Production Printing Engine
 * Dispatches to specialized templates based on script type.
 */
export const handlePrintScript = ({
    title,
    content,
    scriptType,
    ownerName,
    formattedDuration
}: PrintOptions) => {
    // 1. Select Template Logic
    const isDialogue = scriptType === 'DIALOGUE';
    const printBody = isDialogue 
        ? generateDialogueHtml(content) 
        : generateMonologueHtml(content);
    
    const specificStyles = isDialogue ? dialogueStyles : monologueStyles;

    // 2. Open Print Window
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const today = format(new Date(), 'dd/MM/yyyy');

    printWindow.document.write(`
        <!DOCTYPE html>
        <html lang="th">
        <head>
            <meta charset="UTF-8">
            <title>${title} - Script</title>
            <link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@400;700&family=Courier+Prime:wght@400;700&display=swap" rel="stylesheet">
            <style>
                ${commonStyles}
                ${specificStyles}
            </style>
        </head>
        <body>
            <div class="header">
                <div class="title-container">
                    <div class="title">${title}</div>
                    <div class="meta">
                        WRITTEN BY: ${ownerName || 'UNKNOWN'}<br/>
                        TYPE: ${scriptType}
                    </div>
                </div>
                <div class="stats-box">
                    DATE: ${today}<br/>
                    DURATION: ${formattedDuration}
                </div>
            </div>

            <div class="script-body">
                ${printBody}
            </div>

            <div class="footer">
                <div>GENERATED BY JUIJUI SCRIPT ENGINE</div>
                <div>${title} • ${today} • PAGE <span class="page-number"></span></div>
            </div>

            <script>
                window.onload = function() { 
                    document.querySelectorAll('.page-number').forEach(el => {
                        el.textContent = "1";
                    });
                    
                    setTimeout(() => {
                        window.print(); 
                    }, 500);
                }
            </script>
        </body>
        </html>
    `);
    printWindow.document.close();
};
