import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
// Fix: Added MasterOption to imports
import { MeetingLog, MeetingCategory, User, MeetingAgendaItem, TaskAsset, MasterOption } from '../../types';
import { format } from 'date-fns';
import { useToast } from '../../context/ToastContext';

// Import Refactored Sub-components
import MeetingHeader from './MeetingHeader';
import MeetingNavigation from './MeetingNavigation';
import MeetingNotesTab from './MeetingNotesTab';
import MeetingDecisionsTab from './MeetingDecisionsTab';

interface MeetingDetailProps {
    meeting: MeetingLog;
    users: User[];
    
    // State Controls (Passed from Parent MeetingView)
    title: string;
    setTitle: (val: string) => void;
    date: Date;
    setDate: (val: Date) => void;
    category: MeetingCategory;
    setCategory: (val: MeetingCategory) => void;
    projectTag: string;
    setProjectTag: (val: string) => void;
    attendees: string[];
    onToggleAttendee: (id: string) => void;
    
    content: string;
    setContent: (val: string) => void;
    
    decisions: string;
    setDecisions: (val: string) => void;

    activeTab: 'NOTES' | 'ACTIONS' | 'DECISIONS';
    setActiveTab: (val: 'NOTES' | 'ACTIONS' | 'DECISIONS') => void;
    
    isSaving: boolean;
    onBlurUpdate: (field: string, value: any) => void;
    
    // Fix: Added masterOptions prop definition
    masterOptions: MasterOption[];

    children?: React.ReactNode; 
}

const MeetingDetail: React.FC<MeetingDetailProps> = ({
    meeting, users,
    title, setTitle, date, setDate, category, setCategory, projectTag, setProjectTag, attendees, onToggleAttendee,
    content, setContent, decisions, setDecisions, activeTab, setActiveTab,
    // Fix: Destructure masterOptions from props
    isSaving, onBlurUpdate, masterOptions, children
}) => {
    const { showToast } = useToast();
    
    // Local State specific to this UI (not persisted in parent usually, or complex objects)
    const [agenda, setAgenda] = useState<MeetingAgendaItem[]>(meeting.agenda || []);
    const [assets, setAssets] = useState<TaskAsset[]>(meeting.assets || []);
    
    // UI Toggles
    const [isCopied, setIsCopied] = useState(false);
    const [isExpanded, setIsExpanded] = useState(false);

    // --- Sync Effect ---
    useEffect(() => {
        setAgenda(meeting.agenda || []);
        setAssets(meeting.assets || []);
    }, [meeting.id]); 

    // --- Logic Handlers ---

    const handleAddAgenda = (topic: string) => {
        const newItem: MeetingAgendaItem = {
            id: crypto.randomUUID(),
            topic: topic,
            isCompleted: false
        };
        const newAgenda = [...agenda, newItem];
        setAgenda(newAgenda);
        onBlurUpdate('agenda', newAgenda);
    };

    const toggleAgenda = (id: string) => {
        const newAgenda = agenda.map(item => item.id === id ? { ...item, isCompleted: !item.isCompleted } : item);
        setAgenda(newAgenda);
        onBlurUpdate('agenda', newAgenda);
    };

    const deleteAgenda = (id: string) => {
        const newAgenda = agenda.filter(item => item.id !== id);
        setAgenda(newAgenda);
        onBlurUpdate('agenda', newAgenda);
    };
    
    // REFACTORED: Now accepts name and url directly
    const handleAddLink = (name: string, url: string) => {
        const newAsset: TaskAsset = {
            id: crypto.randomUUID(),
            name: name,
            url: url,
            type: 'LINK',
            category: 'LINK',
            createdAt: new Date()
        };
        const newAssets = [...assets, newAsset];
        setAssets(newAssets);
        onBlurUpdate('assets', newAssets);
    };

    const handleCopySummary = () => {
        const attendeeNames = users.filter(u => attendees.includes(u.id)).map(u => u.name).join(', ');
        const agendaText = agenda.map(a => `${a.isCompleted ? '✅' : '⬜'} ${a.topic}`).join('\n');
        
        const summary = `
📝 *สรุปการประชุม: ${title}*
📅 วันที่: ${format(date, 'd MMM yyyy')}
👥 ผู้เข้าประชุม: ${attendeeNames || '-'}

📌 *วาระการประชุม (Agenda):*
${agendaText || '- ไม่มีวาระ -'}

💬 *บันทึก (Notes):*
${content}

✨ *มติที่ประชุม (Decisions):*
${decisions || '-'}

🔗 *ลิงก์ที่เกี่ยวข้อง:*
${assets.map(a => `- ${a.name}: ${a.url}`).join('\n')}

_Generated by Juijui Planner_ 🍹
        `.trim();

        navigator.clipboard.writeText(summary);
        setIsCopied(true);
        showToast('คัดลอกสรุปแล้ว! พร้อมส่งในไลน์ครับผม', 'success');
        setTimeout(() => setIsCopied(false), 2000);
    };

    // --- Layout Classes ---
    const containerClasses = isExpanded
        ? "fixed inset-0 z-[9999] w-screen h-[100dvh] bg-[#FFF9F2] flex flex-col"
        : "flex-1 flex flex-col overflow-hidden bg-[#FFF9F2] relative transition-all duration-500";

    const detailView = (
        <div className={containerClasses}>
            
            {/* Decorative BG */}
            <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'radial-gradient(#4f46e5 2px, transparent 2px)', backgroundSize: '24px 24px' }}></div>

            {/* Part 1: Header */}
            <MeetingHeader 
                title={title} setTitle={setTitle} onBlurTitle={() => onBlurUpdate('title', title)}
                date={date} setDate={setDate} onBlurDate={(d) => onBlurUpdate('date', d)}
                category={category} setCategory={setCategory} onBlurCategory={(c) => onBlurUpdate('category', c)}
                projectTag={projectTag} setProjectTag={setProjectTag} onBlurTag={(t) => onBlurUpdate('tags', [t])}
                attendees={attendees} onToggleAttendee={onToggleAttendee}
                users={users}
                // Fix: Pass masterOptions to MeetingHeader
                masterOptions={masterOptions}
                isExpanded={isExpanded} onToggleExpand={() => setIsExpanded(!isExpanded)}
                isCopied={isCopied} onCopySummary={handleCopySummary}
            />

            {/* Part 2: Navigation */}
            <MeetingNavigation 
                activeTab={activeTab} 
                setActiveTab={setActiveTab} 
            />

            {/* Part 3: Body Content */}
            <div className={`flex-1 overflow-hidden flex flex-col relative`}>
                
                {activeTab === 'NOTES' && (
                    <MeetingNotesTab 
                        key={meeting.id} // FORCE REMOUNT: Using ID as key to reset state on switch
                        agenda={agenda}
                        onAddAgenda={handleAddAgenda}
                        onToggleAgenda={toggleAgenda}
                        onDeleteAgenda={deleteAgenda}
                        assets={assets}
                        onAddAsset={handleAddLink}
                        
                        // FIX: Use 'meeting.content' (source of truth) for initialization instead of potentially stale 'content' prop
                        content={meeting.content || ''}
                        
                        // Keep setContent to update parent state for autosave
                        setContent={setContent}
                        onBlurContent={() => onBlurUpdate('content', content)}
                    />
                )}

                {activeTab === 'ACTIONS' && (
                    <div className="flex-1 overflow-hidden relative flex flex-col">
                         {children}
                    </div>
                )}

                {activeTab === 'DECISIONS' && (
                    <MeetingDecisionsTab 
                        decisions={decisions}
                        setDecisions={setDecisions}
                        onBlurDecisions={() => onBlurUpdate('decisions', decisions)}
                    />
                )}
            </div>
        </div>
    );

    // Render Portal if Expanded
    if (isExpanded) {
        return createPortal(detailView, document.body);
    }

    return detailView;
};

export default MeetingDetail;