
import React, { useState } from 'react';
import { MeetingLog, MeetingCategory, User, MeetingAgendaItem, TaskAsset } from '../../types';
import { Calendar, Check, BookOpen, CheckSquare, Share2, Hash, Users, List, Copy, ClipboardCheck, Plus, Trash2, Link as LinkIcon, Paperclip } from 'lucide-react';
import { format } from 'date-fns';
import { th } from 'date-fns/locale';
import { useToast } from '../../context/ToastContext';

interface MeetingDetailProps {
    meeting: MeetingLog;
    users: User[];
    
    // State Controls
    title: string;
    setTitle: (val: string) => void;
    date: Date;
    setDate: (val: Date) => void;
    category: MeetingCategory;
    setCategory: (val: MeetingCategory) => void;
    projectTag: string;
    setProjectTag: (val: string) => void;
    attendees: string[];
    onToggleAttendee: (id: string) => void;
    
    content: string;
    setContent: (val: string) => void;
    
    activeTab: 'NOTES' | 'ACTIONS' | 'DECISIONS';
    setActiveTab: (val: 'NOTES' | 'ACTIONS' | 'DECISIONS') => void;
    
    isSaving: boolean;
    onBlurUpdate: (field: string, value: any) => void;
    
    children?: React.ReactNode; 
}

const CATEGORY_OPTIONS: { id: MeetingCategory, label: string, color: string }[] = [
    { id: 'GENERAL', label: 'General / Weekly', color: 'bg-gray-100 text-gray-700' },
    { id: 'PROJECT', label: 'Production / Project', color: 'bg-orange-50 text-orange-700' },
    { id: 'CRISIS', label: 'Crisis / Urgent', color: 'bg-red-50 text-red-700' },
    { id: 'CREATIVE', label: 'Creative / Brainstorm', color: 'bg-purple-50 text-purple-700' },
    { id: 'HR', label: 'HR / Personnel', color: 'bg-teal-50 text-teal-700' },
];

const MeetingDetail: React.FC<MeetingDetailProps> = ({
    meeting, users,
    title, setTitle, date, setDate, category, setCategory, projectTag, setProjectTag, attendees, onToggleAttendee,
    content, setContent, activeTab, setActiveTab,
    isSaving, onBlurUpdate, children
}) => {
    const { showToast } = useToast();
    const [agenda, setAgenda] = useState<MeetingAgendaItem[]>(meeting.agenda || []);
    const [assets, setAssets] = useState<TaskAsset[]>(meeting.assets || []);
    const [newAgendaTopic, setNewAgendaTopic] = useState('');
    const [isCopied, setIsCopied] = useState(false);

    // --- Agenda Logic ---
    const handleAddAgenda = () => {
        if(!newAgendaTopic.trim()) return;
        const newItem: MeetingAgendaItem = {
            id: crypto.randomUUID(),
            topic: newAgendaTopic,
            isCompleted: false
        };
        const newAgenda = [...agenda, newItem];
        setAgenda(newAgenda);
        setNewAgendaTopic('');
        onBlurUpdate('agenda', newAgenda);
    };

    const toggleAgenda = (id: string) => {
        const newAgenda = agenda.map(item => item.id === id ? { ...item, isCompleted: !item.isCompleted } : item);
        setAgenda(newAgenda);
        onBlurUpdate('agenda', newAgenda);
    };

    const deleteAgenda = (id: string) => {
        const newAgenda = agenda.filter(item => item.id !== id);
        setAgenda(newAgenda);
        onBlurUpdate('agenda', newAgenda);
    };

    // --- Asset Logic (Simplified for Demo) ---
    const handleAddLink = () => {
        const url = prompt('ใส่ลิงก์เอกสาร / รูปภาพ (URL):');
        if (url) {
            const newAsset: TaskAsset = {
                id: crypto.randomUUID(),
                name: 'Attached Link',
                url: url,
                type: 'LINK',
                category: 'LINK',
                createdAt: new Date()
            };
            const newAssets = [...assets, newAsset];
            setAssets(newAssets);
            onBlurUpdate('assets', newAssets);
        }
    };

    // --- Export Summary Logic ---
    const handleCopySummary = () => {
        const attendeeNames = users.filter(u => attendees.includes(u.id)).map(u => u.name).join(', ');
        const agendaText = agenda.map(a => `${a.isCompleted ? '✅' : '⬜'} ${a.topic}`).join('\n');
        
        // Extract Decisions (Assuming they are in a specific format or just from content for now, ideally separate field)
        // For V1, we'll just use the content field as the main body.
        
        const summary = `
📅 *สรุปการประชุม: ${title}*
🗓️ วันที่: ${format(date, 'd MMM yyyy', { locale: th })}
👥 ผู้เข้าประชุม: ${attendeeNames || '-'}

📌 *วาระการประชุม (Agenda):*
${agendaText || '- ไม่มีวาระ -'}

📝 *รายละเอียด / บันทึก:*
${content}

🔗 *ลิงก์ที่เกี่ยวข้อง:*
${assets.map(a => `- ${a.url}`).join('\n')}

_Generated by Juijui Planner_
        `.trim();

        navigator.clipboard.writeText(summary);
        setIsCopied(true);
        showToast('คัดลอกสรุปการประชุมแล้ว! ไปวางใน Line ได้เลย', 'success');
        setTimeout(() => setIsCopied(false), 2000);
    };
    
    const theme = (() => {
        switch(category) {
            case 'CRISIS': return 'red';
            case 'PROJECT': return 'orange';
            case 'CREATIVE': return 'purple';
            case 'HR': return 'teal';
            default: return 'indigo';
        }
    })();

    return (
        <div className="flex-1 flex flex-col overflow-hidden bg-white">
            
            {/* Header Area */}
            <div className={`px-8 py-6 border-b border-gray-100 flex flex-col gap-4 relative overflow-hidden`}>
                <div className={`absolute top-0 right-0 w-32 h-32 bg-${theme}-50 rounded-bl-full opacity-50 pointer-events-none transition-colors duration-500`} />

                <div className="flex justify-between items-start relative z-10">
                    <input 
                        type="text" 
                        className={`text-3xl font-black w-full outline-none bg-transparent border-b-2 border-transparent focus:border-${theme}-200 transition-colors pb-1 placeholder:text-gray-300 text-gray-800`}
                        placeholder="หัวข้อการประชุม..."
                        value={title}
                        onChange={e => setTitle(e.target.value)}
                        onBlur={() => onBlurUpdate('title', title)}
                    />
                    
                    <div className="flex gap-2 shrink-0 ml-4">
                         {/* Copy Summary Button */}
                        <button 
                            onClick={handleCopySummary}
                            className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-2 transition-all shadow-sm active:scale-95 ${isCopied ? 'bg-green-100 text-green-700' : 'bg-white border border-gray-200 text-gray-600 hover:text-indigo-600 hover:border-indigo-200'}`}
                            title="คัดลอกสรุปไปวางในแชท"
                        >
                            {isCopied ? <ClipboardCheck className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                            {isCopied ? 'Copied' : 'Copy Summary'}
                        </button>

                        <div className="relative group">
                            <button className={`px-3 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wider flex items-center gap-2 transition-all ${CATEGORY_OPTIONS.find(c => c.id === category)?.color}`}>
                                {CATEGORY_OPTIONS.find(c => c.id === category)?.label}
                            </button>
                            <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-xl shadow-xl border border-gray-100 p-1 hidden group-hover:block z-50 animate-in fade-in zoom-in-95">
                                {CATEGORY_OPTIONS.map(opt => (
                                    <button
                                        key={opt.id}
                                        onClick={() => { setCategory(opt.id); onBlurUpdate('category', opt.id); }}
                                        className={`w-full text-left px-3 py-2 text-xs font-bold rounded-lg hover:bg-gray-50 flex items-center justify-between ${category === opt.id ? 'text-gray-900 bg-gray-50' : 'text-gray-500'}`}
                                    >
                                        {opt.label}
                                        {category === opt.id && <Check className="w-3 h-3 text-green-500" />}
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                <div className="flex flex-wrap items-center gap-3 relative z-10">
                    <div className="flex items-center text-sm text-gray-500 bg-gray-50 px-3 py-1.5 rounded-lg border border-gray-200 hover:border-gray-300 transition-colors">
                        <Calendar className={`w-4 h-4 mr-2 text-${theme}-500`} />
                        <input 
                            type="date" 
                            className="bg-transparent outline-none font-bold text-gray-700 cursor-pointer"
                            value={format(date, 'yyyy-MM-dd')}
                            onChange={e => {
                                const d = new Date(e.target.value);
                                setDate(d);
                                onBlurUpdate('date', d.toISOString());
                            }}
                        />
                    </div>

                    {(category === 'PROJECT' || category === 'CREATIVE' || projectTag) && (
                        <div className={`flex items-center text-sm px-3 py-1.5 rounded-lg border transition-all group focus-within:ring-2 focus-within:ring-${theme}-100 ${projectTag ? `bg-${theme}-50 border-${theme}-100 text-${theme}-700` : 'bg-gray-50 border-gray-200 text-gray-500'}`}>
                            <Hash className={`w-4 h-4 mr-2 ${projectTag ? `text-${theme}-500` : 'text-gray-400'}`} />
                            <input 
                                type="text" 
                                className={`bg-transparent outline-none font-bold w-32 focus:w-48 transition-all placeholder:text-gray-300 ${projectTag ? `text-${theme}-800` : 'text-gray-600'}`}
                                placeholder="Project Tag..."
                                value={projectTag}
                                onChange={e => setProjectTag(e.target.value)}
                                onBlur={() => onBlurUpdate('tags', [projectTag])}
                            />
                        </div>
                    )}

                    <div className="flex items-center gap-2 ml-auto">
                        <div className="flex -space-x-2">
                            {attendees.map(uid => {
                                const u = users.find(user => user.id === uid);
                                return u ? <img key={uid} src={u.avatarUrl} className="w-8 h-8 rounded-full border-2 border-white bg-gray-200" title={u.name} /> : null;
                            })}
                            <div className="relative group/add">
                                <button className="w-8 h-8 rounded-full bg-gray-100 border-2 border-white flex items-center justify-center text-gray-400 hover:bg-gray-200 text-xs font-bold hover:text-gray-600 transition-colors">
                                    <Users className="w-4 h-4" />
                                </button>
                                <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-xl shadow-xl border border-gray-100 p-2 hidden group-hover/add:block z-50 max-h-60 overflow-y-auto">
                                    {users.filter(u => u.isActive).map(u => {
                                        const isPresent = attendees.includes(u.id);
                                        return (
                                            <button key={u.id} onClick={() => onToggleAttendee(u.id)} className="w-full flex items-center gap-2 p-2 hover:bg-gray-50 rounded-lg text-left">
                                                <img src={u.avatarUrl} className="w-6 h-6 rounded-full" />
                                                <span className={`text-xs font-bold flex-1 ${isPresent ? 'text-indigo-600' : 'text-gray-600'}`}>{u.name}</span>
                                                {isPresent && <Check className="w-3 h-3 text-green-500" />}
                                            </button>
                                        )
                                    })}
                                </div>
                            </div>
                        </div>
                    </div>
                    {isSaving && <span className="text-xs text-gray-400 animate-pulse ml-2">Saving...</span>}
                </div>
            </div>

            {/* Tabs */}
            <div className="px-8 pt-2 border-b border-gray-100 flex gap-6 shrink-0 bg-white sticky top-0 z-10">
                <button 
                    onClick={() => setActiveTab('NOTES')}
                    className={`pb-3 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activeTab === 'NOTES' ? `border-${theme}-600 text-${theme}-600` : 'border-transparent text-gray-400 hover:text-gray-600'}`}
                >
                    <BookOpen className="w-4 h-4" /> วาระ & บันทึก (Agenda & Notes)
                </button>
                <button 
                    onClick={() => setActiveTab('ACTIONS')}
                    className={`pb-3 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activeTab === 'ACTIONS' ? 'border-orange-500 text-orange-600' : 'border-transparent text-gray-400 hover:text-gray-600'}`}
                >
                    <CheckSquare className="w-4 h-4" /> สิ่งที่ต้องทำ (Tasks)
                </button>
                <button 
                    onClick={() => setActiveTab('DECISIONS')}
                    className={`pb-3 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activeTab === 'DECISIONS' ? 'border-green-500 text-green-600' : 'border-transparent text-gray-400 hover:text-gray-600'}`}
                >
                    <Share2 className="w-4 h-4" /> มติ (Decisions)
                </button>
            </div>

            {/* Content Area */}
            <div className={`flex-1 overflow-hidden flex flex-col bg-gray-50/30 relative`}>
                {activeTab === 'NOTES' && (
                    <div className="flex-1 p-8 overflow-y-auto flex flex-col gap-6">
                        
                        {/* AGENDA SECTION */}
                        <div className="bg-white p-5 rounded-2xl border border-gray-200 shadow-sm">
                            <h3 className="text-sm font-bold text-gray-700 mb-3 flex items-center uppercase tracking-wide">
                                <List className="w-4 h-4 mr-2" /> วาระการประชุม (Agenda)
                            </h3>
                            <div className="space-y-2">
                                {agenda.map((item, idx) => (
                                    <div key={item.id} className="flex items-center gap-3 group">
                                        <button 
                                            onClick={() => toggleAgenda(item.id)}
                                            className={`w-5 h-5 rounded border flex items-center justify-center transition-colors ${item.isCompleted ? 'bg-green-500 border-green-500 text-white' : 'border-gray-300 hover:border-indigo-400'}`}
                                        >
                                            {item.isCompleted && <Check className="w-3.5 h-3.5" />}
                                        </button>
                                        <span className={`text-sm flex-1 ${item.isCompleted ? 'text-gray-400 line-through' : 'text-gray-800'}`}>
                                            {item.topic}
                                        </span>
                                        <button onClick={() => deleteAgenda(item.id)} className="text-gray-300 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <Trash2 className="w-4 h-4" />
                                        </button>
                                    </div>
                                ))}
                                
                                {/* Add Agenda Input */}
                                <div className="flex items-center gap-3 pt-2">
                                    <div className="w-5 h-5 rounded border border-dashed border-gray-300 flex items-center justify-center text-gray-400">
                                        <Plus className="w-3 h-3" />
                                    </div>
                                    <input 
                                        type="text" 
                                        className="flex-1 bg-transparent text-sm outline-none placeholder:text-gray-400"
                                        placeholder="เพิ่มวาระการประชุม..."
                                        value={newAgendaTopic}
                                        onChange={e => setNewAgendaTopic(e.target.value)}
                                        onKeyDown={e => { if(e.key === 'Enter') handleAddAgenda(); }}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* ATTACHMENTS SECTION */}
                        {(assets.length > 0) && (
                            <div className="flex flex-wrap gap-2">
                                {assets.map(asset => (
                                    <a key={asset.id} href={asset.url} target="_blank" className="flex items-center gap-2 px-3 py-1.5 bg-white border border-gray-200 rounded-lg text-xs text-gray-600 hover:text-indigo-600 hover:border-indigo-200 transition-all shadow-sm">
                                        <Paperclip className="w-3 h-3" /> {asset.name || asset.url}
                                    </a>
                                ))}
                                <button onClick={handleAddLink} className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-lg text-xs text-gray-500 font-bold transition-all">
                                    <Plus className="w-3 h-3" /> แนบลิงก์
                                </button>
                            </div>
                        )}
                        {assets.length === 0 && (
                            <button onClick={handleAddLink} className="flex items-center gap-2 text-xs text-gray-400 hover:text-indigo-600 w-fit">
                                <LinkIcon className="w-3 h-3" /> แนบไฟล์/ลิงก์ประกอบ
                            </button>
                        )}

                        {/* NOTES TEXTAREA */}
                        <div className="flex-1 min-h-[300px] relative">
                            <textarea 
                                className="w-full h-full bg-transparent outline-none resize-none text-gray-700 leading-relaxed text-base font-medium placeholder:text-gray-300"
                                placeholder="เริ่มจดบันทึกการประชุมที่นี่... (รองรับ Markdown พื้นฐาน)"
                                value={content}
                                onChange={e => setContent(e.target.value)}
                            />
                        </div>
                    </div>
                )}

                {activeTab === 'ACTIONS' && (
                    children 
                )}

                {activeTab === 'DECISIONS' && (
                    <div className="flex-1 p-8 overflow-y-auto">
                        <div className="bg-white p-8 rounded-2xl border-2 border-dashed border-green-100 h-full">
                            <h3 className="text-green-700 font-bold uppercase tracking-wider text-xs mb-4 flex items-center">
                                <Check className="w-4 h-4 mr-2" /> สรุปมติที่ประชุม (Key Decisions)
                            </h3>
                            <textarea 
                                className="w-full h-[90%] bg-transparent outline-none resize-none text-gray-700 leading-relaxed"
                                placeholder="- อนุมัติงบประมาณโปรเจกต์ X...&#10;- เลื่อนกำหนดการถ่ายทำเป็นวันจันทร์หน้า...&#10;- เปลี่ยนธีมสีหลักเป็นสีส้ม..."
                                // For V1, using main content storage but ideally should separate field in future, sharing with content for now or add new field
                                // NOTE: In real implementation, bind this to a separate 'decisions' field if available, or just append to content.
                            />
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default MeetingDetail;
