
import React, { forwardRef } from 'react';
import { Duty, User } from '../../../types';
import { format } from 'date-fns';

interface ExportTemplateProps {
    groupedDuties: { date: Date; duties: Duty[] }[];
    users: User[];
}

const ExportTemplate = forwardRef<HTMLDivElement, ExportTemplateProps>(({ groupedDuties, users }, ref) => {
    return (
        <div 
            ref={ref}
            style={{ 
                position: 'fixed', 
                top: '-9999px', 
                left: '-9999px', 
                width: '800px', 
                padding: '40px',
                background: '#ffffff',
                fontFamily: 'sans-serif'
            }}
        >
            {/* Export Header */}
            <div className="flex items-center justify-between mb-8 border-b-2 border-gray-100 pb-6">
                <div>
                    <h1 className="text-3xl font-black text-gray-800 mb-2">📋 ตารางเวร (Duty Roster)</h1>
                    <p className="text-lg text-gray-500 font-medium">
                        ประจำวันที่ {groupedDuties.length > 0 ? `${format(groupedDuties[0].date, 'd MMM')} - ${format(groupedDuties[groupedDuties.length - 1].date, 'd MMM yyyy')}` : ''}
                    </p>
                </div>
                <div className="flex items-center gap-2 bg-indigo-50 px-4 py-2 rounded-xl border border-indigo-100">
                    <span className="text-2xl">🧹</span>
                    <span className="text-indigo-800 font-bold">Juijui Planner</span>
                </div>
            </div>

            {/* Export Grid */}
            <div className="space-y-4">
                {groupedDuties.map((group) => (
                    <div key={`exp-${group.date.toISOString()}`} className="flex border border-gray-200 rounded-2xl overflow-hidden shadow-sm">
                        {/* Date Box */}
                        <div className="w-32 bg-indigo-50 border-r border-indigo-100 flex flex-col items-center justify-center p-4">
                            <span className="text-indigo-400 text-sm font-bold uppercase tracking-wider mb-1">
                                {format(group.date, 'EEEE')}
                            </span>
                            <span className="text-4xl font-black text-indigo-700">
                                {format(group.date, 'd')}
                            </span>
                            <span className="text-indigo-500 text-xs font-bold mt-1">
                                {format(group.date, 'MMM')}
                            </span>
                        </div>

                        {/* People Box */}
                        <div className="flex-1 bg-white p-4">
                            <div className="grid grid-cols-2 gap-4">
                                {group.duties.map((duty, i) => {
                                    const u = users.find(user => user.id === duty.assigneeId);
                                    return (
                                        <div key={i} className="flex items-center gap-3 p-2 rounded-xl border border-gray-100 bg-gray-50/50">
                                            {u?.avatarUrl ? (
                                                <img src={u.avatarUrl} className="w-10 h-10 rounded-full border-2 border-white shadow-sm object-cover" />
                                            ) : (
                                                <div className="w-10 h-10 rounded-full bg-gray-300 border-2 border-white"></div>
                                            )}
                                            <div>
                                                <p className="font-bold text-gray-800">{u?.name || 'Unknown'}</p>
                                                <p className="text-xs text-gray-500">{duty.title}</p>
                                            </div>
                                        </div>
                                    )
                                })}
                            </div>
                        </div>
                    </div>
                ))}
            </div>

             <div className="mt-8 text-center text-gray-400 text-sm font-medium">
                Generated by Juijui Planner System • {format(new Date(), 'dd/MM/yyyy HH:mm')}
            </div>
        </div>
    );
});

export default ExportTemplate;
